[tool.poetry]
name = "bottle-ssl"
version = "0.1.0"
description = "A simple web page using BottlePy and SSL"
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]

[tool.poetry.dependencies]
python = "*"
beaker = "^1.10"
cheroot = "^6.5"
bottle = "^0.12.16"

[tool.poetry.dev-dependencies]
pytest = "^4.4"
requests = "^2.21"
